language: r
r:
  - devel
  - release
sudo: false
cache: packages
latex: false


r-github-packages:
  - jimhester/covr

after_success:
  - tar -C .. -xf $PKG_TARBALL
  - Rscript -e 'covr::coveralls()'
  